#### CS61A Spring 2025
# Chapter 3.3 Exception 
#### Sean Villegas


Gold:

```python
>>> def invert(x):
        result = 1/x  # Raises a ZeroDivisionError if x is 0
        print('Never printed if x is 0')
        return result
>>> def invert_safe(x):
        try:
            return invert(x)
        except ZeroDivisionError as e:
            return str(e)
>>> invert_safe(2)
Never printed if x is 0
0.5
>>> invert_safe(0)
'division by zero'
```
- This example illustrates that the print expression in invert is never **evaluated**
    - and instead control is transferred to the suite of the except clause in invert_safe.
    - Which coerces the `ZeroDivisionError e` to a string gives the **human-interpretable** string returned by invert_safe: `'division by zero'`.

#
Exception objects themselves can have attributes, such as the error message stated in an assert statement and information about where in the course of execution the exception was raised. User-defined exception classes can have additional attributes.

```python
>>> class IterImproveError(Exception):
        def __init__(self, last_guess):
            self.last_guess = last_guess
```